### ISSUE TITLE
RFC indexer: configuration with JSONAlchemy

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio#2718]
I studied a little bit the internal representation of indexes and I'd like to propose a starting point to create the indexes configuration.
Then, we can discuss about it and improve/evolve it.
(Please, correct me if something is not syntactically written correctly. I don't know exactly the potentiality of JSONAlchemy)

**Problem**
Create a JSONAlchemy file configuration to represent all indexes configuration

**Proposal**
```yaml

fields:
  collection:
    code: collection
    option_w: "value_w"
  ...

indexes:
  # Index foobar
  foobar:
    description: "foo bar"
    translations:
      deutsch: "foo bour"
      italian: "fuu bar"
    fields: 'collection', 'field_code_1'
    stemming_language: 'it'
    synonym_kbrs: 'FAQ', 'exact'
    remove: 'stopwords', 'html_markup', 'latex_markup'
    indexers:
      # Native indexer specific configuration
      native:
        tokenizer: 'BibIndexJournalTokenizer'
        option_y: 'value_y'
        # execute this functions in cascade before indexed the field
        pre_execute: 'function1', 'function2'
        # execute this functions in cascade after indexed the field
        post_execute: 'function1', 'function2'
      # Virtual indexer specific configuration
      virtual:
        tokenizer: 'BibIndexJournalTokenizer'
        option_z: 'value_z'
        # execute this functions in cascade before indexed the field
        pre_execute: 'function1', 'function2'
        # execute this functions in cascade after indexed the field
        post_execute: 'function1', 'function2'
      # Elastic Search indexer specific configuration
      elastic_search:
        tokenizer: 'es_tokenizer_1'
        option_x: 'value_x'
        # execute this functions in cascade before indexed the field
        pre_execute: 'function1', 'function2'
        # execute this functions in cascade after indexed the field
        post_execute: 'function1', 'function2'
  # Index barfoo
  barfoo:
    ...
```
@jirikuncar @marioskogias @kaplun
